"""Consent gate.

Real presenter media may not be processed until ``CONSENT.md`` records written
consent. Everything under ``assets/samples/`` is generated by this repo (synthetic
placeholders, no identifiable person) and is exempt.

This is a safety interlock, not a security boundary — it is here to make the
"don't touch real media yet" rule impossible to forget, not to stop a determined
user who edits the file dishonestly.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from core.config import REPO_ROOT, JobConfig

CONSENT_FILE = REPO_ROOT / "CONSENT.md"

#: Directories whose contents are synthetic placeholders and need no consent.
EXEMPT_DIRS = (REPO_ROOT / "assets" / "samples",)

_STATUS_RE = re.compile(r"^\s*\**\s*STATUS:\s*([A-Z_ ]+?)\s*\**\s*$", re.MULTILINE)
_PLACEHOLDER_RE = re.compile(r"<[^>\n]+>")

REQUIRED_FIELDS = (
    "Presenter name",
    "Consent obtained on",
    "Signed document location",
    "Scope of use granted",
    "Voice cloning permitted",
    "Likeness / lip-sync synthesis permitted",
    "Recorded by",
)


class ConsentError(RuntimeError):
    """Raised when a job would touch real media without recorded consent."""


def _read_consent() -> str:
    if not CONSENT_FILE.is_file():
        return ""
    return CONSENT_FILE.read_text(encoding="utf-8")


def consent_status() -> tuple[bool, list[str]]:
    """Return ``(granted, problems)`` describing the current consent record."""
    text = _read_consent()
    if not text:
        return False, [f"{CONSENT_FILE.name} is missing"]

    problems: list[str] = []
    match = _STATUS_RE.search(text)
    status = (match.group(1).strip() if match else "MISSING").upper()
    if status != "GRANTED":
        problems.append(f"{CONSENT_FILE.name} status is {status!r}, expected 'GRANTED'")
        return False, problems

    # Status says granted — make sure the record was actually filled in.
    for label in REQUIRED_FIELDS:
        row = re.search(rf"^-\s+\*\*{re.escape(label)}[^:]*:\*\*\s*(.+)$", text, re.MULTILINE)
        if row is None:
            problems.append(f"missing field in {CONSENT_FILE.name}: {label}")
            continue
        value = row.group(1).strip().strip("`").strip()
        if not value or _PLACEHOLDER_RE.search(value):
            problems.append(f"unfilled field in {CONSENT_FILE.name}: {label}")

    return (not problems), problems


def is_exempt(path: Path) -> bool:
    """True if ``path`` is a synthetic placeholder that needs no consent."""
    try:
        resolved = path.resolve()
    except OSError:
        return False
    for base in EXEMPT_DIRS:
        try:
            resolved.relative_to(base.resolve())
            return True
        except ValueError:
            continue
    return False


def assert_allowed(cfg: JobConfig) -> None:
    """Raise :class:`ConsentError` if this job needs consent it does not have."""
    real_assets = [
        ("video.presenter_clip", cfg.presenter_clip),
        ("voice.reference_audio", cfg.reference_audio),
    ]
    needs_consent = [(k, p) for k, p in real_assets if p is not None and not is_exempt(p)]
    if not needs_consent:
        return

    granted, problems = consent_status()
    if granted:
        return

    listed = "\n".join(f"    - {k}: {p}" for k, p in needs_consent)
    detail = "\n".join(f"    - {p}" for p in problems)
    raise ConsentError(
        "Refusing to run: this job uses assets outside assets/samples/, which are "
        "treated as real presenter media.\n"
        f"  Assets requiring consent:\n{listed}\n"
        f"  Consent gate problems:\n{detail}\n"
        f"  Fill in {CONSENT_FILE} and set its status to GRANTED, or point the job at "
        "the synthetic placeholders in assets/samples/."
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Inspect the presenter consent gate.")
    ap.add_argument("--check", action="store_true", help="exit non-zero if consent is not granted")
    args = ap.parse_args(argv)

    granted, problems = consent_status()
    if granted:
        print("CONSENT: GRANTED — real presenter media is permitted.")
        return 0

    print("CONSENT: NOT GRANTED — only assets/samples/ placeholders may be used.")
    for p in problems:
        print(f"  - {p}")
    return 1 if args.check else 0


if __name__ == "__main__":
    sys.exit(main())
